#ifndef NUKLEON_RULES_H
#define NUKLEON_RULES_H

#define NK_RULE_STATE_FPS_TARGET 10
#define NK_RULE_TOTAL_TICKS_FOR_MELTDOWN_WIPE 5
#define NK_RULE_GAME_REACTOR_STARTING_MAX_HEAT 1000.0
#define NK_RULE_GAME_REACTOR_STARTING_MAX_POWER 100.0
#define NK_RULE_GAME_REACTOR_STARTING_SELF_DISSIPATION_HEAT_RATE 0.1
#define NK_STATE_RUN_SECONDS -1.0

#endif